#!/bin/bash

# Caveat emptor: Extremely ad hoc, won't ever work outside of snake root
# directory.
exec ../MoarVM/install/bin/moar --execname="$0" --libpath=blib \
    --libpath=../MoarVM/install/share/nqp/lib blib/snake.moarvm "$@"
